#!/usr/bin/env bash
# core_config.sh -- core configuration for miyoko's shellbot

# CONF: bot
nick=""
channel=""
server=""
port=""

# CONF: mod_nickserv
ns_user=""

# CONF: fantasy prefix
prefix=">"

# CONF: owner pass (try ./shellbot.sh -H <password>)
owner_pass=""

# EXPERIMENTAL[NOTYETIMPLEMENTED]: quiet
# suppresses the noise generated by telnet (it still gets logged)
core_quiet="no"

# CORE: debug
# run the bot in bash debug mode
core_debug="no"

# CORE: backgrounding
# run the bot in the background with nohup
core_bck="yes"

# CORE: reconnect on error
# if the bot receives an ERROR:, do we restart?
core_reconn="yes"